- name: Backend Setup
  hosts: all
  become: yes
  tasks:
    - name: Disable default NodeJS Version Module
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Enable NodeJS module for V20
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Adding Application User
      ansible.builtin.user:
        name: expense

    - name: Clean the Old content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create App Directory    
      ansible.builtin.file:
        path: /app
        state: directory
        
    - name: Download and Extract App content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
        dest: /app
        remote_src: yes
        
    - name: Download NodeJS Dependencies
      community.general.npm:
        path: /app
        state: latest
        
    - name: Copy Backend Service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Install Mysql Client
      ansible.builtin.dnf:
        name: mysql
        state: installed

    - name: Load Schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        login_host: 172.31.37.250

    - name: Start Backend Service
      ansible.builtin.systemd_service:
        name: backend
        state: restarted
        enabled: yes
        daemon_reload: yes

  
  
