- name: Install Mysql Server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start Mysql Server
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: yes

- name: Install Python Mysql Client
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9

- name: Check the DB connection with our password
  community.mysql.mysql_info:
    login_user: root
    login_password: ExpenseApp@1
    login_host: 172.31.37.250
    filter: version
  register: mysql_connection_output

- name: Print
  debug:
    msg: "{{ mysql_connection_output }}"

- name: Setup Mysql Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
  when: mysql_connection_output.failed is true